# golangci-lint v2 configuration
version: "2"

run:
  timeout: 5m
  tests: true

# Use recommended defaults + a few extras
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - gosec
    - misspell
    - unconvert
    - unparam
    - prealloc

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    
  govet:
    enable:
      - shadow
      
  gosec:
    excludes:
      - G104
      
  gocritic:
    enabled-tags:
      - diagnostic
      - performance

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

output:
  formats:
    colored-line-number:
      path: stdout
